// Veil Installer — minimum viable Phase 3.5 GUI.
//
// Three deploy paths are sketched here. Only the "Docker" path is
// fully implemented in this revision; the SSH and Edge paths are
// stubbed and surface a "coming soon" notice. The intent is to
// land the navigation shell and the Docker output flow first, then
// fill in the remote-install paths in subsequent commits.

import { invoke } from "@tauri-apps/api/core";

const root = document.getElementById("app");
const state = { route: "home", form: {} };

function render() {
  root.innerHTML = "";
  switch (state.route) {
    case "home":
      renderHome();
      break;
    case "docker":
      renderDocker();
      break;
    case "ssh":
    case "edge":
      renderComingSoon(state.route);
      break;
  }
}

function el(tag, props = {}, ...children) {
  const e = document.createElement(tag);
  for (const [k, v] of Object.entries(props)) {
    if (k === "class") e.className = v;
    else if (k === "html") e.innerHTML = v;
    else if (k.startsWith("on")) e.addEventListener(k.slice(2).toLowerCase(), v);
    else e.setAttribute(k, v);
  }
  for (const c of children) {
    if (c == null) continue;
    e.append(typeof c === "string" ? document.createTextNode(c) : c);
  }
  return e;
}

function nav(route) {
  state.route = route;
  render();
}

function renderHome() {
  root.append(
    el("h1", {}, "Veil installer"),
    el("p", { class: "subtitle" }, "Choose how you want to deploy your server."),
    el("div", { class: "choice-grid" },
      choice("Docker", "Generate a docker-compose.yml you can scp to a host with Docker installed.", () => nav("docker")),
      choice("VPS via SSH", "Connect to a fresh VPS and install via SSH (planned).", () => nav("ssh")),
      choice("Edge function", "Deploy to Deno Deploy / Fly.io as an edge proxy (planned).", () => nav("edge")),
    ),
    el("div", { class: "notice" },
      el("strong", {}, "Pre-alpha. "),
      "This installer is in early development. The Docker workflow generates a working compose file; SSH and Edge are scaffolds for upcoming work."
    ),
  );
}

function choice(title, desc, onclick) {
  return el("button", { class: "choice", onclick },
    el("div", { class: "title" }, title),
    el("div", { class: "desc" }, desc));
}

function renderDocker() {
  const f = state.form;

  const onChange = (key) => (ev) => { f[key] = ev.target.value; };

  const fieldsCard = el("div", {},
    el("h2", {}, "Server parameters"),
    field("Public host name (e.g. vps.example.com)", "domain", f.domain || "", onChange("domain")),
    field("Reality target SNI (real domain to splice probes to)", "target_sni", f.target_sni || "www.cloudflare.com", onChange("target_sni")),
    field("Admin email (for ACME / Let's Encrypt)", "email", f.email || "", onChange("email")),
    field("Veil container image", "image", f.image || "ghcr.io/redstone-md/veil:dev", onChange("image")),
  );

  const out = el("textarea", { readonly: "" });
  out.value = generateCompose(f);

  const actions = el("div", { class: "actions" },
    el("button", { onclick: () => nav("home") }, "← Back"),
    el("div", { class: "spacer" }),
    el("button", { onclick: () => { out.value = generateCompose(f); } }, "Regenerate"),
    el("button", { class: "primary", onclick: () => copy(out.value) }, "Copy"),
    el("button", { onclick: () => save(out.value) }, "Save…"),
  );

  // Re-render output on every input change.
  fieldsCard.querySelectorAll("input").forEach(inp => {
    inp.addEventListener("input", () => { out.value = generateCompose(f); });
  });

  root.append(
    el("h1", {}, "Docker compose"),
    el("p", { class: "subtitle" }, "Fill in the server parameters; the compose file regenerates as you type."),
    fieldsCard,
    el("h2", {}, "compose.yaml"),
    out,
    actions,
  );
}

function field(label, name, value, oninput) {
  const wrap = el("div");
  wrap.append(
    el("label", { for: name }, label),
    el("input", { name, value, oninput }),
  );
  return wrap;
}

function generateCompose(f) {
  const domain    = f.domain    || "vps.example.com";
  const targetSNI = f.target_sni || "www.cloudflare.com";
  const email     = f.email     || "ops@example.com";
  const image     = f.image     || "ghcr.io/redstone-md/veil:dev";
  return `# Generated by veil-installer.
# Drop this onto a host with Docker installed and run:
#   docker compose up -d
#
# Then create your admin login and add at least one user:
#   docker compose exec veil veil admin user-create --db /var/lib/veil/users.db --username root
#   docker compose exec veil veil user add --db /var/lib/veil/users.db --name alice --pubkey '<paste>'

services:
  veil:
    image: ${image}
    container_name: veil
    restart: unless-stopped
    ports:
      - "443:443/tcp"   # Reality / WSS
      - "443:443/udp"   # QUIC (same port, different protocol)
    volumes:
      - veil-state:/var/lib/veil
      - ./server.yaml:/etc/veil/server.yaml:ro
    healthcheck:
      test: ["CMD", "/usr/local/bin/veil", "version"]
      interval: 30s
      timeout: 5s
      retries: 3
      start_period: 5s

volumes:
  veil-state:

# ---------- write the file below as ./server.yaml ----------
#
# transports:
#   - type: reality
#     listen: "0.0.0.0:443"
#     target_sni: "${targetSNI}"
#     target_addr: "${targetSNI}:443"
#     domain:     "${domain}"
#
# acme:
#   email:     "${email}"
#   cache_dir: "/var/lib/veil/acme"
#
# static_key_path: "/var/lib/veil/server.key"
# user_db_path:    "/var/lib/veil/users.db"
`;
}

function renderComingSoon(route) {
  root.append(
    el("h1", {}, route === "ssh" ? "VPS via SSH" : "Edge function"),
    el("p", { class: "subtitle" }, "Not yet implemented in this revision."),
    el("div", { class: "notice" },
      "The ", el("strong", {}, route === "ssh" ? "SSH" : "edge-function"), " workflow is on the Phase 3.5+ roadmap. ",
      "Until it lands, use the Docker compose path or follow the manual install in ",
      el("code", {}, "docs/INSTALL.md"), "."
    ),
    el("div", { class: "actions" },
      el("button", { onclick: () => nav("home") }, "← Back"),
    ),
  );
}

async function copy(text) {
  try {
    await navigator.clipboard.writeText(text);
  } catch {
    // Fallback when clipboard API is unavailable in webview.
    const ta = document.createElement("textarea");
    ta.value = text; document.body.appendChild(ta); ta.select();
    document.execCommand("copy"); document.body.removeChild(ta);
  }
}

async function save(text) {
  // The Tauri side exposes a `save_compose` command that opens a
  // native file dialog and writes the result. When running outside
  // Tauri (e.g. plain `vite` for UI iteration) we fall back to
  // download via a Blob URL.
  if (typeof invoke === "function" && typeof window.__TAURI__ !== "undefined") {
    try {
      await invoke("save_compose", { content: text });
      return;
    } catch (e) {
      console.error(e);
    }
  }
  const blob = new Blob([text], { type: "text/yaml" });
  const url = URL.createObjectURL(blob);
  const a = document.createElement("a");
  a.href = url; a.download = "compose.yaml"; a.click();
  URL.revokeObjectURL(url);
}

render();
